# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: ptech
    ports:
      - 25432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8050:8080

  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
        - NODE_ENV=development
    volumes:
        - ./:/home/node/app
    ports:
        - 8080:8080
    command: "node src/index"
    depends_on: 
        - db